export {Main} from './Main/Main'
export {Navbar} from './Navbar/Navbar'
export {Slider} from './Slider/Slider'
export {NavigateButtons} from './NavigateButtons/NavigateButtons'
export {FilteredProduct} from './FilteredProduct/FilteredProduct'
export {SingleProduct} from './FilteredProduct/SingleProduct'
export {Cart} from './Cart/Cart'